export enum ERROR_MESSAGE {
  INVALID_CREDENTIALS = "Invalid username or password",
  USER_NOT_FOUND = "User not found",
  USER_DEACTIVATED = "User account deactivated",
  INVALID_TOKEN = "Invalid token",
  TOKEN_EXPIRED = "Token expired",
  INVALID_PASSWORD = "Invalid password",
  INVALID_USER = "Invalid user",
  INVALID_ROLE = "Invalid role",
  INVALID_REQUEST = "Invalid request",
  UNAUTHORIZED_ACCESS = "Unauthorized access",
  ACCESS_DENIED = "Access denied",
  FORBIDDEN = "Forbidden",
  NOT_FOUND = "Not found",
  METHOD_NOT_ALLOWED = "Method not allowed",
  CONFLICT = "Conflict",
  INTERNAL_SERVER_ERROR = "Internal server error",
  SERVICE_UNAVAILABLE = "Service unavailable",
  UNEXPECTED = "An unexpected error occurred",
}
